version: '3'

services: 
  java:
    build: 
      context: backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes: 
      - ${PWD}/backend/target/dsvendas-0.0.1-SNAPSHOT.jar:/app/dsvendas.jar
    command: java -jar dsvendas.jar
    ports: 
      - 8081:8081
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    volumes: 
      - .docker/dbdata:/var/lib/postgresql
  pgadmin:
    image: adminer
    ports:
      - 8080:8080
  node:
    build: 
      context: frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes: 
      - ${PWD}/frontend:/app
      - /app/node_modules/
    command: yarn start
    ports: 
      - 3000:3000